/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visualizacoes;

import modelos.Reader;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import modelos.*;
import sun.awt.UngrabEvent;

/**
 *
 * @author ezequieloliveira
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    Reader r = new Reader();
    University universidade = r.readUniversityFile("universidade.txt");

    public Main() {
        initComponents();

        universidade.setCourses(r.readCoursesFile("courses.txt"));

        this.txtNomeUniversidade.setText(universidade.getName());
        this.labelUniversidadeNome.setText(universidade.getName());
        this.reloadTable();
    }

    public void reloadTable() {
        DefaultTableModel modeloAluno = new DefaultTableModel();
        modeloAluno.setColumnCount(3);
        modeloAluno.setColumnIdentifiers(new Object[]{"Código", "Nome", "Titulo"});

        Object[] list = new Object[3];

        DefaultComboBoxModel filtroAlunos = new DefaultComboBoxModel();
        DefaultComboBoxModel filtroCursos = new DefaultComboBoxModel();
        DefaultComboBoxModel filtroAlunosMat = new DefaultComboBoxModel();
        DefaultComboBoxModel filtroCursosMat = new DefaultComboBoxModel();

        filtroCursos.addElement("Filtrar curso");
        filtroAlunos.addElement("Filtrar aluno");

        for (Student s : universidade.getStudentsArray()) {
            list[0] = s.getId();
            list[1] = s.getName();
            if (s instanceof UnderGraduateStudent) {
                list[2] = "GRADUANDO";
            } else {
                list[2] = "PÓS-GRADUANDO";
            }
            modeloAluno.addRow(list);
            filtroAlunos.addElement(s.getId());
            filtroAlunosMat.addElement(s.getId());
        }

        DefaultTableModel modeloCurso = new DefaultTableModel();
        modeloCurso.setColumnCount(3);
        modeloCurso.setColumnIdentifiers(new Object[]{"Código", "Titulo", "Número de créditos", "Máximo de alunos"});

        Object[] listCurso = new Object[4];

        for (Course c : universidade.getCoursesArray()) {
            listCurso[0] = c.getCode();
            listCurso[1] = c.getTitle();
            listCurso[2] = c.getNumCredits();
            listCurso[3] = c.getMaxStudents();
            modeloCurso.addRow(listCurso);
            filtroCursos.addElement(c.getCode());
            filtroCursosMat.addElement(c.getCode());
        }

        jComboBoxAlunosFiltrar.setModel(filtroAlunos);
        jComboBoxCursosFiltrar.setModel(filtroCursos);
        jComboBoxAlunoMat.setModel(filtroAlunosMat);
        jComboBoxCursoMat.setModel(filtroCursosMat);

        tabelaAlunos.setModel(modeloAluno);
        tabelaCursos.setModel(modeloCurso);
    }

    public void saveTXT() {
        r.writeCoursesFile("courses.txt", (ArrayList<Course>) universidade.getCoursesArray());
        r.writeRegistrationFile("registrations.txt", universidade.getRegistrations());
        r.writeUniversityFile("universidade.txt", universidade);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvas1 = new java.awt.Canvas();
        mainTab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtNomeUniversidade = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        labelUniversidadeNome = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaAlunos = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTiaAluno = new javax.swing.JTextField();
        txtNomeAluno = new javax.swing.JTextField();
        txtTelefoneAluno = new javax.swing.JTextField();
        txtEmailAluno = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtEnderecoAluno = new javax.swing.JTextArea();
        jComboBoxSelecionarTitulo = new javax.swing.JComboBox();
        buttonGerenciarAluno = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaCursos = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCodigoCurso = new javax.swing.JTextField();
        txtTituloCurso = new javax.swing.JTextField();
        txtNumCreditosCurso = new javax.swing.JTextField();
        txtNumVagasCurso = new javax.swing.JTextField();
        buttonManagerCourse = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tabelaRegistros = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jComboBoxAlunosFiltrar = new javax.swing.JComboBox();
        jComboBoxCursosFiltrar = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        jPanel10 = new javax.swing.JPanel();
        jComboBoxSemMat = new javax.swing.JComboBox();
        jComboBoxAlunoMat = new javax.swing.JComboBox();
        jComboBoxCursoMat = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        txtAnoMat = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnRemoverRegistro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Mudar nome");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomeUniversidade)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 332, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(labelUniversidadeNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(labelUniversidadeNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNomeUniversidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(329, Short.MAX_VALUE))
        );

        mainTab.addTab("Principal", jPanel1);

        tabelaAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Titulo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaAlunos.setCellSelectionEnabled(true);
        tabelaAlunos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tabelaAlunosFocusLost(evt);
            }
        });
        tabelaAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaAlunosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaAlunos);

        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
        });

        jLabel1.setText("TIA");

        jLabel2.setText("Nome");

        jLabel3.setText("Telefone");

        jLabel4.setText("E-mail");

        jLabel5.setText("Endereço");

        txtTiaAluno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTiaAlunoFocusLost(evt);
            }
        });

        txtEnderecoAluno.setColumns(20);
        txtEnderecoAluno.setRows(5);
        jScrollPane4.setViewportView(txtEnderecoAluno);

        jComboBoxSelecionarTitulo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione um titulo", "Graduação", "Pós-Graduação" }));
        jComboBoxSelecionarTitulo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxSelecionarTituloItemStateChanged(evt);
            }
        });

        buttonGerenciarAluno.setText("Cadastrar Aluno");
        buttonGerenciarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGerenciarAlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonGerenciarAluno)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxSelecionarTitulo, 0, 160, Short.MAX_VALUE)
                            .addComponent(txtTiaAluno)
                            .addComponent(txtNomeAluno)
                            .addComponent(txtTelefoneAluno)
                            .addComponent(txtEmailAluno)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtTiaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addComponent(txtTelefoneAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addComponent(txtEmailAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jComboBoxSelecionarTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(buttonGerenciarAluno))
        );

        jScrollPane3.setViewportView(jPanel7);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainTab.addTab("Alunos", jPanel2);

        tabelaCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Número de créditos", "Máximo de estudantes"
            }
        ));
        tabelaCursos.setBounds(new java.awt.Rectangle(0, 0, 371, 64));
        tabelaCursos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tabelaCursosFocusLost(evt);
            }
        });
        tabelaCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaCursosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaCursos);

        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });

        jLabel6.setText("Código");

        jLabel7.setText("Titulo");

        jLabel8.setText("Número Créditos");

        jLabel9.setText("Máximo de vagas");

        buttonManagerCourse.setText("Adicionar");
        buttonManagerCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonManagerCourseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonManagerCourse)
                        .addGap(116, 116, 116))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumVagasCurso))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                .addComponent(txtNumCreditosCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTituloCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCodigoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(129, 129, 129))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCodigoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTituloCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNumCreditosCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtNumVagasCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(buttonManagerCourse)
                .addGap(30, 30, 30))
        );

        jScrollPane6.setViewportView(jPanel6);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6)
        );

        jScrollPane5.setViewportView(jPanel8);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5))
        );

        mainTab.addTab("Cursos", jPanel3);

        tabelaRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Aluno", "Curso"
            }
        ));
        tabelaRegistros.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tabelaRegistrosFocusLost(evt);
            }
        });
        tabelaRegistros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaRegistrosMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tabelaRegistros);

        jComboBoxAlunosFiltrar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxAlunosFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAlunosFiltrarActionPerformed(evt);
            }
        });

        jComboBoxCursosFiltrar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton2.setText("Mostrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxAlunosFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxCursosFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(33, 33, 33))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxAlunosFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCursosFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jComboBoxSemMat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));

        jComboBoxAlunoMat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxCursoMat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton3.setText("Cadastrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel10.setText("ANO");

        jLabel11.setText("SEM.");

        btnRemoverRegistro.setText("Remover");
        btnRemoverRegistro.setEnabled(false);
        btnRemoverRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jComboBoxAlunoMat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxCursoMat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBoxSemMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel10Layout.createSequentialGroup()
                                    .addGap(16, 16, 16)
                                    .addComponent(jLabel11)))
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel10Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtAnoMat, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                                .addGroup(jPanel10Layout.createSequentialGroup()
                                    .addGap(45, 45, 45)
                                    .addComponent(jLabel10)))))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoverRegistro)))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(2, 2, 2)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxSemMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAnoMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jComboBoxAlunoMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxCursoMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(btnRemoverRegistro))
                .addGap(18, 18, 18))
        );

        jScrollPane8.setViewportView(jPanel10);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainTab.addTab("Registros", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTab)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTab)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        universidade.setName(txtNomeUniversidade.getText());
        this.labelUniversidadeNome.setText(universidade.getName());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buttonGerenciarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGerenciarAlunoActionPerformed
        // TODO add your handling code here:

        Student tmpStudent;

        Long id = null;

        if (buttonGerenciarAluno.getText() == "Cadastrar Aluno") {
            try {
                id = Long.parseLong(txtTiaAluno.getText());
                if (jComboBoxSelecionarTitulo.getSelectedItem() == "Pós-Graduação") {
                    String thesisTitle = null;
                    String supervisor = null;
                    while (thesisTitle == null) {
                        thesisTitle = JOptionPane.showInputDialog(rootPane, "Tese do aluno");
                    }

                    while (supervisor == null) {
                        supervisor = JOptionPane.showInputDialog(rootPane, "Supervisor do aluno");
                    }
                    tmpStudent = new PostGraduateStudent(thesisTitle, supervisor, id, txtNomeAluno.getText(), txtEnderecoAluno.getText(), txtTelefoneAluno.getText(), txtEmailAluno.getText());
                    universidade.addStudent(tmpStudent);
                } else if (jComboBoxSelecionarTitulo.getSelectedItem() == "Graduação") {
                    String major = "";
                    String minor = "";
                    while (major == "") {
                        major = JOptionPane.showInputDialog(rootPane, "Grande área do aluno");
                    }
                    while (minor == "") {
                        minor = JOptionPane.showInputDialog(rootPane, "Especialização do aluno");
                    }
                    tmpStudent = new UnderGraduateStudent(major, minor, id, txtNomeAluno.getText(), txtEnderecoAluno.getText(), txtTelefoneAluno.getText(), txtEmailAluno.getText());
                    universidade.addStudent(tmpStudent);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Selecione o titulo", "Selecione o titulo", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Somente números no código do aluno!", "Somente números no código do aluno!", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            try {
                id = Long.parseLong(txtTiaAluno.getText());
                if (jComboBoxSelecionarTitulo.getSelectedItem() == "Pós-Graduação") {
                    String thesisTitle = null;
                    String supervisor = null;
                    while (thesisTitle == null) {
                        thesisTitle = JOptionPane.showInputDialog(rootPane, "Tese do aluno");
                    }

                    while (supervisor == null) {
                        supervisor = JOptionPane.showInputDialog(rootPane, "Supervisor do aluno");
                    }
//                    tmpStudent = new PostGraduateStudent(thesisTitle, supervisor, id, txtNomeAluno.getText(), txtEnderecoAluno.getText(), txtTelefoneAluno.getText(), txtEmailAluno.getText());
                    universidade.updatePostGraduateStudent(id, txtNomeAluno.getText(), txtTelefoneAluno.getText(), txtEnderecoAluno.getText(), txtEmailAluno.getText(), thesisTitle, supervisor);
                } else if (jComboBoxSelecionarTitulo.getSelectedItem() == "Graduação") {
                    String major = "";
                    String minor = "";
                    while (major == "") {
                        major = JOptionPane.showInputDialog(rootPane, "Grande área do aluno");
                    }
                    while (minor == "") {
                        minor = JOptionPane.showInputDialog(rootPane, "Especialização do aluno");
                    }
//                    tmpStudent = new UnderGraduateStudent(major, minor, id, txtNomeAluno.getText(), txtEnderecoAluno.getText(), txtTelefoneAluno.getText(), txtEmailAluno.getText());
//                    universidade.addStudent(tmpStudent);
                    universidade.updateUnderGraduateStudent(id, txtNomeAluno.getText(), txtEnderecoAluno.getText(), txtTelefoneAluno.getText(), txtEmailAluno.getText(), major, minor);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Selecione o titulo", "Selecione o titulo", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Somente números no código do aluno!", "Somente números no código do aluno!", JOptionPane.ERROR_MESSAGE);
            }
        }

        txtEmailAluno.setText(null);
        txtEnderecoAluno.setText(null);
        txtNomeAluno.setText(null);
        txtTelefoneAluno.setText(null);
        txtTiaAluno.setText(null);

        reloadTable();
        saveTXT();
//        DefaultTableModel modelo = (DefaultTableModel) tabelaAlunos.getModel();
//        modelo.fireTableDataChanged();
    }//GEN-LAST:event_buttonGerenciarAlunoActionPerformed

    private void jComboBoxSelecionarTituloItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxSelecionarTituloItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSelecionarTituloItemStateChanged

    String selectedIdStudent = null;

    private void tabelaAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaAlunosMouseClicked
        // TODO add your handling code here:
        selectedIdStudent = tabelaAlunos.getModel().getValueAt(tabelaAlunos.getSelectedRow(), 0).toString();
        System.out.println(tabelaAlunos.getModel().getValueAt(tabelaAlunos.getSelectedRow(), tabelaAlunos.getSelectedColumn()));
        if (tabelaAlunos.getModel().getValueAt(tabelaAlunos.getSelectedRow(), 2) == "GRADUANDO") {
            Student tmpStudent = universidade.getStudent(Long.parseLong(tabelaAlunos.getModel().getValueAt(tabelaAlunos.getSelectedRow(), 0).toString()));
            txtNomeAluno.setText(tmpStudent.getName());
            txtTiaAluno.setText(tmpStudent.getId().toString());
            txtEnderecoAluno.setText(tmpStudent.getAddress());
            txtTelefoneAluno.setText(tmpStudent.getPhone());
            txtEmailAluno.setText(tmpStudent.getEmail());
        } else if (tabelaAlunos.getModel().getValueAt(tabelaAlunos.getSelectedRow(), 2) == "PÓS-GRADUANDO") {
            Student tmpStudent = universidade.getStudent(Long.parseLong(tabelaAlunos.getModel().getValueAt(tabelaAlunos.getSelectedRow(), 0).toString()));
            txtNomeAluno.setText(tmpStudent.getName());
            txtTiaAluno.setText(tmpStudent.getId().toString());
            txtEnderecoAluno.setText(tmpStudent.getAddress());
            txtTelefoneAluno.setText(tmpStudent.getPhone());
            txtEmailAluno.setText(tmpStudent.getEmail());
        }
        buttonGerenciarAluno.setText("Alterar Aluno");
    }//GEN-LAST:event_tabelaAlunosMouseClicked

    private void tabelaAlunosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tabelaAlunosFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_tabelaAlunosFocusLost

    private void txtTiaAlunoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTiaAlunoFocusLost
        // TODO add your handling code here:
        if (txtTiaAluno.getText() == null ? selectedIdStudent != null : !txtTiaAluno.getText().equals(selectedIdStudent)) {
            buttonGerenciarAluno.setText("Cadastrar Aluno");
        }
    }//GEN-LAST:event_txtTiaAlunoFocusLost

    String selectedCourse = null;

    private void buttonManagerCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonManagerCourseActionPerformed

        switch (buttonManagerCourse.getText()) {
            case "Adicionar":
                // TODO add your handling code here:
                Course cursoTMP;
                try {
                    cursoTMP = new Course(txtCodigoCurso.getText(), txtTituloCurso.getText(), Integer.parseInt(txtNumCreditosCurso.getText()), Integer.parseInt(txtNumVagasCurso.getText()));
                    universidade.getCoursesArray().add(cursoTMP);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, e);
                }
                txtCodigoCurso.setText(null);
                txtTituloCurso.setText(null);
                txtNumCreditosCurso.setText(null);
                txtNumVagasCurso.setText(null);
                break;
            case "Alterar":
                try {
                    universidade.updateCourse(selectedCourse, txtTituloCurso.getText(), Integer.parseInt(txtNumCreditosCurso.getText()), Integer.parseInt(txtNumVagasCurso.getText()));
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, e);
                }
                break;
        }

        this.reloadTable();
        saveTXT();
    }//GEN-LAST:event_buttonManagerCourseActionPerformed

    private void tabelaCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaCursosMouseClicked
        // TODO add your handling code here:
        Course courseTMP = universidade.getCourse(tabelaCursos.getModel().getValueAt(tabelaCursos.getSelectedRow(), 0).toString());
        txtCodigoCurso.setText(courseTMP.getCode());
        selectedCourse = txtCodigoCurso.getText();
        txtTituloCurso.setText(courseTMP.getTitle());
        txtNumCreditosCurso.setText(courseTMP.getNumCredits().toString());
        txtNumVagasCurso.setText(courseTMP.getMaxStudents().toString());
        buttonManagerCourse.setText("Alterar");
    }//GEN-LAST:event_tabelaCursosMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modeloRegistros = new DefaultTableModel();
        modeloRegistros.setColumnCount(3);
        modeloRegistros.setColumnIdentifiers(new Object[]{"Aluno", "Curso"});

        Object[] listaRegistros = new Object[4];

        List<Registration> regs = new ArrayList<>();

        if (jComboBoxAlunosFiltrar.getSelectedItem().toString() != "Filtrar aluno") {
            try {
                for (Course c : universidade.getCoursesArray()) {
                    Registration r = universidade.getRegistration(Long.parseLong(jComboBoxAlunosFiltrar.getSelectedItem().toString()), c.getCode());
                    if (r != null) {
                        regs.add(r);
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e.toString());
            }
        } else if (jComboBoxAlunosFiltrar.getSelectedItem() != "Filtrar curso") {
            try {
                for (Student s : universidade.getStudentsArray()) {
                    Registration r = universidade.getRegistration(s.getId(), jComboBoxCursosFiltrar.getSelectedItem().toString());
                    if (r != null) {
                        regs.add(r);
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e.toString());
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Erro");
        }

        for (Registration r : regs) {
            listaRegistros[0] = r.getStudent().getId();
            listaRegistros[1] = r.getCourse().getCode();
            modeloRegistros.addRow(listaRegistros);
        }

        tabelaRegistros.setModel(modeloRegistros);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (universidade.registerStudent(Long.parseLong(jComboBoxAlunoMat.getSelectedItem().toString()), jComboBoxCursoMat.getSelectedItem().toString(), Integer.parseInt(txtAnoMat.getText()), Integer.parseInt(jComboBoxSemMat.getSelectedItem().toString()))) {
            JOptionPane.showMessageDialog(rootPane, "Matricula realizada com sucesso!");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Matricula não realizada.");
        }
        saveTXT();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBoxAlunosFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAlunosFiltrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxAlunosFiltrarActionPerformed

    private void tabelaRegistrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaRegistrosMouseClicked
        // TODO add your handling code here:
        btnRemoverRegistro.setEnabled(true);
        regSelected = universidade.getRegistration(Long.parseLong(tabelaRegistros.getModel().getValueAt(tabelaRegistros.getSelectedRow(), 0).toString()), tabelaRegistros.getModel().getValueAt(tabelaRegistros.getSelectedRow(), 1).toString());
    }//GEN-LAST:event_tabelaRegistrosMouseClicked

    Registration regSelected = null;

    private void btnRemoverRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverRegistroActionPerformed
        // TODO add your handling code here:
        universidade.removeregistro(regSelected);
        reloadTable();
    }//GEN-LAST:event_btnRemoverRegistroActionPerformed

    private void tabelaRegistrosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tabelaRegistrosFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaRegistrosFocusLost

    private void tabelaCursosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tabelaCursosFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaCursosFocusLost

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
        buttonManagerCourse.setText("Adicionar");
        txtNumCreditosCurso.setText(null);
        txtNumVagasCurso.setText(null);
        txtCodigoCurso.setText(null);
        txtTituloCurso.setText(null);
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        // TODO add your handling code here:
        buttonGerenciarAluno.setText("Cadastrar Aluno");
        txtEmailAluno.setText(null);
        txtEnderecoAluno.setText(null);
        txtNomeAluno.setText(null);
        txtTelefoneAluno.setText(null);
        txtTiaAluno.setText(null);
    }//GEN-LAST:event_jPanel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRemoverRegistro;
    private javax.swing.JButton buttonGerenciarAluno;
    private javax.swing.JButton buttonManagerCourse;
    private java.awt.Canvas canvas1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBoxAlunoMat;
    private javax.swing.JComboBox jComboBoxAlunosFiltrar;
    private javax.swing.JComboBox jComboBoxCursoMat;
    private javax.swing.JComboBox jComboBoxCursosFiltrar;
    private javax.swing.JComboBox jComboBoxSelecionarTitulo;
    private javax.swing.JComboBox jComboBoxSemMat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JLabel labelUniversidadeNome;
    private javax.swing.JTabbedPane mainTab;
    private javax.swing.JTable tabelaAlunos;
    private javax.swing.JTable tabelaCursos;
    private javax.swing.JTable tabelaRegistros;
    private javax.swing.JTextField txtAnoMat;
    private javax.swing.JTextField txtCodigoCurso;
    private javax.swing.JTextField txtEmailAluno;
    private javax.swing.JTextArea txtEnderecoAluno;
    private javax.swing.JTextField txtNomeAluno;
    private javax.swing.JTextField txtNomeUniversidade;
    private javax.swing.JTextField txtNumCreditosCurso;
    private javax.swing.JTextField txtNumVagasCurso;
    private javax.swing.JTextField txtTelefoneAluno;
    private javax.swing.JTextField txtTiaAluno;
    private javax.swing.JTextField txtTituloCurso;
    // End of variables declaration//GEN-END:variables

}
